_wandb:
    value:
        cli_version: 0.21.0
        e:
            t6vz9ee68mt3s3n3tt6hmpz9q9xvwmkf:
                codePath: 01-03-network_analysis_emissions_wandb.ipynb
                codePathLocal: 01-03-network_analysis_emissions_wandb.ipynb
                email: jl.liam.gao@gmail.com
                executable: /opt/homebrew/opt/python@3.13/bin/python3.13
                git:
                    commit: 48b073b07a15e0d65a0c93cbe625ce4e99f6183e
                    remote: https://github.com/ImperialCollegeLondon/ECRI-RCDS-Hackathon.git
                host: IC-DV24MPJ2Q6
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/jgao/github/ECRI-RCDS-Hackathon/01-03-network_analysis_emissions_wandb.ipynb
                python: CPython 3.13.5
                root: /Users/jgao/github/ECRI-RCDS-Hackathon
                startedAt: "2025-07-04T18:47:01.856036Z"
                writerId: t6vz9ee68mt3s3n3tt6hmpz9q9xvwmkf
        m: []
        python_version: 3.13.5
        t:
            "3":
                - 2
                - 13
            "4": 3.13.5
            "5": 0.21.0
            "8":
                - 1
            "12": 0.21.0
            "13": darwin-arm64
